# Generated by Django 5.2.10 on 2026-01-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('game_over', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('previous_board', models.JSONField(default=list)),
                ('previous_score', models.IntegerField(default=0)),
                ('can_undo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
