# Generated by Django 5.2.10 on 2026-03-31

from django.db import migrations


def add_undo_fields(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    
    # 检查并添加 can_undo 字段
    cursor.execute("""
        SELECT COUNT(*) FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'game_gamesession' 
        AND COLUMN_NAME = 'can_undo'
    """)
    if cursor.fetchone()[0] == 0:
        cursor.execute("ALTER TABLE game_gamesession ADD COLUMN can_undo bool NOT NULL DEFAULT 0")
    
    # 检查并添加 previous_board 字段
    cursor.execute("""
        SELECT COUNT(*) FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'game_gamesession' 
        AND COLUMN_NAME = 'previous_board'
    """)
    if cursor.fetchone()[0] == 0:
        cursor.execute("ALTER TABLE game_gamesession ADD COLUMN previous_board json NOT NULL")
    
    # 检查并添加 previous_score 字段
    cursor.execute("""
        SELECT COUNT(*) FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'game_gamesession' 
        AND COLUMN_NAME = 'previous_score'
    """)
    if cursor.fetchone()[0] == 0:
        cursor.execute("ALTER TABLE game_gamesession ADD COLUMN previous_score int NOT NULL DEFAULT 0")


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_undo_fields),
    ]
