-- 创建数据库
CREATE DATABASE IF NOT EXISTS game2048 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 创建用户并授权
CREATE USER IF NOT EXISTS 'game2048'@'%' IDENTIFIED BY 'game2048pass';
GRANT ALL PRIVILEGES ON game2048.* TO 'game2048'@'%';
FLUSH PRIVILEGES;
